"""Data layer: Parquet store loader + throttled Stooq/Yahoo fetchers.

Research code must only use the loaders (load_universe, load_prices). The fetchers
are for scripts/seed_data.py and scripts/update_data.py — never call them from a
strategy or during an experiment.
"""

from __future__ import annotations

import io
import time
from contextlib import contextmanager
from pathlib import Path

import pandas as pd
import requests
import yaml

ROOT = Path(__file__).resolve().parent.parent
STORE = ROOT / "data" / "store"
UNIVERSE_FILE = ROOT / "data" / "universe.yaml"
# Every priced instrument that was ever a member of a tracked index, plus the
# ETFs. WHEN each stock is eligible is decided by data/membership/intervals.csv,
# not by presence in this file. Generated by scripts/build_membership.py.
UNIVERSE_PIT_FILE = ROOT / "data" / "universe_pit.yaml"
UNIVERSES = {"legacy": UNIVERSE_FILE, "pit": UNIVERSE_PIT_FILE}

OHLCV_COLS = ["open", "high", "low", "close", "volume"]

_STOOQ_URL = "https://stooq.com/q/d/l/?s={symbol}&i=d"
_MIN_REQUEST_INTERVAL = 1.2  # seconds between Stooq requests
_last_request_ts = 0.0


class RateLimitError(RuntimeError):
    """Raised when a data provider signals we exceeded its limits."""


# ---------------------------------------------------------------------------
# Universe
# ---------------------------------------------------------------------------

_ACTIVE = {"universe": "legacy"}


@contextmanager
def using_universe(name: str):
    """Make `name` the universe that `load_universe()` / `instruments()` answer
    for, for the duration of the block. The protocol wraps a strategy call in
    this so a strategy's own `instruments()` lookups see the same universe as
    the price columns it was handed."""
    if name not in UNIVERSES:
        raise ValueError(f"unknown universe {name!r}; one of {sorted(UNIVERSES)}")
    prev = _ACTIVE["universe"]
    _ACTIVE["universe"] = name
    try:
        yield
    finally:
        _ACTIVE["universe"] = prev


def active_universe() -> str:
    return _ACTIVE["universe"]


def load_universe(name: str | None = None) -> dict:
    """Full parsed universe file: {'fx': {...}, 'instruments': [...]}.

    `name` is "legacy" (data/universe.yaml, today's constituents: the v1
    universe) or "pit" (data/universe_pit.yaml); None means the active one."""
    with open(UNIVERSES[name or _ACTIVE["universe"]]) as f:
        return yaml.safe_load(f)


def instruments(
    types: tuple[str, ...] = ("stock", "etf"), universe: str | None = None
) -> list[dict]:
    return [i for i in load_universe(universe)["instruments"] if i["type"] in types]


def instrument_types(universe: str | None = None) -> dict[str, str]:
    """{id: type} for every instrument of a universe."""
    return {i["id"]: i["type"] for i in load_universe(universe)["instruments"]}


def instrument_regions(universe: str | None = None) -> dict[str, str]:
    """{id: listing region} for every instrument of a universe."""
    return {i["id"]: i.get("region", "") for i in load_universe(universe)["instruments"]}


# The cash rate. Protocol v3 pays it on uninvested cash and measures Sharpe on
# returns in excess of it. ^IRX is the 13-week US T-bill discount yield in
# percent; it is fetched by the data-refresh workflow like any other series and
# stored under `id`. Not a universe member: it is never in `prices`.
RATE_SERIES = {"id": "RATE_US3M", "yahoo": "^IRX", "stooq": None, "type": "rate",
               "currency": "USD", "name": "US 13-week T-bill yield (%)"}


def all_series(universe: str | None = None) -> list[dict]:
    """Every series we store for a universe: instruments, FX pairs and the
    cash rate."""
    uni = load_universe(universe)
    fx = [dict(v, type="fx", currency="USD") for v in uni["fx"].values()]
    return uni["instruments"] + fx + [dict(RATE_SERIES)]


# ---------------------------------------------------------------------------
# Store I/O
# ---------------------------------------------------------------------------
#
# Layout: data/store/<YYYY>/<YYYY-MM>.parquet, one long-format file per calendar
# month holding every series' bars for that month (columns: id, date, open,
# high, low, close, volume). The daily refresh therefore rewrites only the
# current month's file, and a closed month never changes again — the repo no
# longer re-commits every series' full history each day. The whole store is
# read once per process and cached; `load_ohlcv` serves slices of that cache.

_STORE_CACHE: dict = {"sig": None, "series": {}}


def store_path(series_id: str | None = None, month: pd.Timestamp | None = None) -> Path:
    """The month file holding `month` (series_id is accepted for backward
    compatibility and ignored: a month file holds every series)."""
    if month is None:
        return STORE
    m = pd.Timestamp(month)
    return STORE / f"{m.year:04d}" / f"{m.year:04d}-{m.month:02d}.parquet"


def _month_files() -> list[Path]:
    return sorted(STORE.glob("[0-9][0-9][0-9][0-9]/[0-9][0-9][0-9][0-9]-[0-9][0-9].parquet"))


def _store_signature(files: list[Path]) -> tuple:
    return tuple((f.name, f.stat().st_mtime_ns, f.stat().st_size) for f in files)


def _read_month(path: Path) -> pd.DataFrame:
    df = pd.read_parquet(path)
    df["date"] = pd.to_datetime(df["date"]).astype("datetime64[ms]")
    return df


def _store_series() -> dict[str, pd.DataFrame]:
    """{series id: date-indexed OHLCV frame} for the whole store.

    Read once per process and cached; `write_many` invalidates the cache, and
    `reload_store()` forces a re-read after an outside change."""
    if _STORE_CACHE["sig"] is not None:
        return _STORE_CACHE["series"]
    files = _month_files()
    sig = _store_signature(files)
    if _STORE_CACHE["sig"] == sig:
        return _STORE_CACHE["series"]
    series: dict[str, pd.DataFrame] = {}
    if files:
        long = pd.concat([_read_month(f) for f in files], ignore_index=True)
        long = long.sort_values(["id", "date"], kind="stable")
        for sid, g in long.groupby("id", sort=False):
            frame = g.set_index("date")[OHLCV_COLS]
            frame.index.name = "Date"
            series[str(sid)] = frame
    _STORE_CACHE.update(sig=sig, series=series)
    return series


def reload_store() -> None:
    _STORE_CACHE["sig"] = None


def store_ids() -> list[str]:
    return sorted(_store_series())


def load_ohlcv(series_id: str) -> pd.DataFrame | None:
    """One series as a date-indexed OHLCV frame, or None if not in the store."""
    df = _store_series().get(series_id)
    return None if df is None else df.copy()


def write_many(frames: dict[str, pd.DataFrame], replace: bool = False) -> None:
    """Merge rows for many series into the store in one pass.

    Idempotent: dedupes on (id, date), keeping the newest row. `replace=True`
    drops a series' existing rows first (a full re-seed). Only the month files
    that receive rows (or lose them, on replace) are rewritten."""
    parts = []
    for sid, df in frames.items():
        if df is None or df.empty:
            continue
        if isinstance(df.columns, pd.MultiIndex):
            raise ValueError(f"{sid}: OHLCV frame has MultiIndex columns {list(df.columns)[:3]}; "
                             f"expected flat {OHLCV_COLS}")
        d = df.copy()
        d.index = pd.to_datetime(d.index).astype("datetime64[ms]")
        for col in OHLCV_COLS:
            if col not in d.columns:
                d[col] = float("nan")
        d = d[OHLCV_COLS].astype(float)
        d = d[~d.index.duplicated(keep="last")]
        d.insert(0, "id", sid)
        parts.append(d.rename_axis("date").reset_index())
    if not parts and not replace:
        return
    new = pd.concat(parts, ignore_index=True) if parts else pd.DataFrame(
        {"date": pd.Series(dtype="datetime64[ms]"), "id": pd.Series(dtype=object),
         **{c: pd.Series(dtype=float) for c in OHLCV_COLS}})
    months = set(new["date"].dt.to_period("M")) if len(new) else set()
    if replace:
        ids = set(frames)
        cached = _store_series()
        for sid in ids:
            old = cached.get(sid)
            if old is not None and len(old):
                months |= set(old.index.to_period("M"))
    for per in sorted(months):
        path = store_path(month=per.to_timestamp())
        chunk = new[new["date"].dt.to_period("M") == per]
        if path.exists():
            old = _read_month(path)
            if replace:
                old = old[~old["id"].isin(set(frames))]
            chunk = pd.concat([old, chunk[old.columns]], ignore_index=True)
        chunk = chunk.drop_duplicates(["id", "date"], keep="last")
        chunk = chunk.sort_values(["id", "date"]).reset_index(drop=True)
        chunk = chunk[["id", "date", *OHLCV_COLS]]
        path.parent.mkdir(parents=True, exist_ok=True)
        if chunk.empty:
            path.unlink(missing_ok=True)
        else:
            chunk.to_parquet(path, index=False, compression="zstd")
    _STORE_CACHE["sig"] = None


def write_ohlcv(series_id: str, df: pd.DataFrame, replace: bool = False) -> None:
    """Merge new rows for one series into the store (see `write_many`)."""
    write_many({series_id: df}, replace=replace)


def last_date(series_id: str) -> pd.Timestamp | None:
    df = _store_series().get(series_id)
    return None if df is None or df.empty else df.index[-1]


# ---------------------------------------------------------------------------
# Research loader
# ---------------------------------------------------------------------------

def _fx_to_usd(currency: str, universe: dict) -> pd.Series:
    """Multiplicative series converting one unit of `currency` to USD."""
    if currency == "USD":
        raise ValueError("no FX needed for USD")
    scale = 1.0
    if currency == "GBX":  # LSE pence
        currency, scale = "GBP", 0.01
    spec = universe["fx"][currency]
    df = load_ohlcv(spec["id"])
    if df is None:
        raise FileNotFoundError(
            f"FX series {spec['id']} missing from store; run scripts/seed_data.py"
        )
    rate = df["close"]
    if spec.get("invert"):
        rate = 1.0 / rate
    return rate * scale


def _raw_panel(
    field: str,
    types: tuple[str, ...],
    universe: dict,
    fx_cache: dict[str, pd.Series],
    convert_fx: bool = True,
) -> pd.DataFrame:
    """One field as a wide frame (dates x instrument ids), sorted, unaligned.

    `convert_fx=False` leaves the series in its native unit — used for volume,
    which is a share count and must not be multiplied by an FX rate.
    """
    cols: dict[str, pd.Series] = {}
    for inst in universe["instruments"]:
        if inst["type"] not in types:
            continue
        df = load_ohlcv(inst["id"])
        if df is None or df.empty:
            continue
        series = df[field].astype(float)
        if inst.get("valid_from"):
            # data before this date failed the builder's quality check
            series = series.loc[inst["valid_from"]:]
        cur = inst["currency"]
        if convert_fx and cur != "USD":
            if cur not in fx_cache:
                fx_cache[cur] = _fx_to_usd(cur, universe)
            fx = fx_cache[cur].reindex(series.index).ffill()
            series = series * fx
        cols[inst["id"]] = series
    if not cols:
        raise FileNotFoundError("data store is empty; run scripts/seed_data.py")
    return pd.DataFrame(cols).sort_index()


def load_prices(
    types: tuple[str, ...] = ("stock", "etf"),
    currency: str = "USD",
    field: str = "close",
    universe: str | None = None,
    start: str | None = None,
) -> pd.DataFrame:
    """Wide frame (dates x instrument ids) of daily prices converted to USD.

    Instruments missing from the store are skipped with a warning column count
    difference; NaN before an instrument's first bar is expected and strategies
    must handle it.
    """
    if currency != "USD":
        raise ValueError("only USD target currency is supported")
    prices = _raw_panel(field, types, load_universe(universe), {})
    if start is not None:
        prices = prices.loc[start:]
    # Drop weekend/garbage rows where nearly nothing traded.
    prices = prices.dropna(how="all")
    # The index is the union of all exchange calendars, so every column has
    # holes on foreign holidays. Forward-fill briefly so rolling windows and
    # returns behave; the cap keeps genuinely dead series NaN (and the engine
    # zeroes weights on NaN prices).
    prices = prices.ffill(limit=10)
    return prices


# Panels a strategy may receive as its optional second argument. `close` is
# omitted: it is `load_prices()`, which the strategy already gets as `prices`.
AUX_FIELDS = ("open", "high", "low", "volume")


def load_panels(
    types: tuple[str, ...] = ("stock", "etf"),
    fields: tuple[str, ...] = AUX_FIELDS,
    universe: str | None = None,
    start: str | None = None,
) -> dict[str, pd.DataFrame]:
    """Auxiliary OHLCV panels aligned to `load_prices()`'s index and columns.

    Every frame shares the close panel's index and column order exactly, so a
    caller can truncate `prices` and the panels by the same slice and know they
    still line up — the property the protocol's causality check depends on.

    - `open`/`high`/`low` are FX-converted to USD like the close, and briefly
      forward-filled on the same 10-day cap, for the same reason.
    - `volume` is a **share count** and is left in native units, un-ffilled: a
      foreign holiday has no volume, and fabricating one would corrupt any
      liquidity measure built on it. Expect NaN there and skip it.
    - `dollar_volume` is close_usd * volume, i.e. USD traded notional — the
      currency-correct input for Amihud-style illiquidity.
    """
    close = load_prices(types=types, universe=universe, start=start)
    uni = load_universe(universe)
    fx_cache: dict[str, pd.Series] = {}
    panels: dict[str, pd.DataFrame] = {}
    for field in fields:
        raw = _raw_panel(field, types, uni, fx_cache, convert_fx=(field != "volume"))
        panel = raw.reindex(index=close.index, columns=close.columns)
        if field != "volume":
            panel = panel.ffill(limit=10)
        panels[field] = panel
    if "volume" in panels:
        panels["dollar_volume"] = panels["volume"] * close
    return panels


def load_traded(
    index: pd.DatetimeIndex, columns, universe: str | None = None,
) -> pd.DataFrame:
    """Bool panel aligned to `load_prices()`: True where the instrument printed
    a real close that day. `load_prices` forward-fills holidays so rolling
    windows behave; an execution model must not fill an order at such a
    stale, carried-forward price."""
    uni = {i["id"]: i for i in load_universe(universe)["instruments"]}
    out = pd.DataFrame(False, index=index, columns=list(columns))
    for col in out.columns:
        df = load_ohlcv(col)
        if df is None or df.empty:
            continue
        close = df["close"]
        valid_from = (uni.get(col) or {}).get("valid_from")
        if valid_from:
            close = close.loc[valid_from:]
        out[col] = close.notna().reindex(index).fillna(False).astype(bool)
    return out


def load_rf(index: pd.DatetimeIndex, required: bool = True) -> pd.Series | None:
    """Daily simple return on cash for each row of `index`, from the stored
    T-bill yield: the yield known at the previous row, accrued over the
    calendar days between the rows (actual/365). The first row accrues
    nothing. Returns None (or raises, if `required`) when the series is not in
    the store yet — the data-refresh workflow seeds it."""
    df = load_ohlcv(RATE_SERIES["id"])
    if df is None or df.empty:
        if required:
            raise FileNotFoundError(
                f"cash-rate series {RATE_SERIES['id']} ({RATE_SERIES['yahoo']}) is not in the "
                f"store; run the data-refresh workflow, which seeds it"
            )
        return None
    yld = df["close"].astype(float).sort_index()
    yld = yld.reindex(yld.index.union(index)).ffill().reindex(index)
    days = pd.Series(index, index=index).diff().dt.days.fillna(0.0)
    rf = (yld.shift(1) / 100.0 * days / 365.0).fillna(0.0)
    return rf.rename("rf")


def slice_panels(panels: dict[str, pd.DataFrame] | None, index) -> dict[str, pd.DataFrame]:
    """Restrict every panel to `index` (a DatetimeIndex, typically a truncated
    price index). The one supported way to narrow a panel dict: doing it by hand
    risks handing a strategy rows its prices cannot see."""
    if not panels:
        return {}
    return {k: v.reindex(index=index) for k, v in panels.items()}


# ---------------------------------------------------------------------------
# Fetchers (scripts only)
# ---------------------------------------------------------------------------

def _throttle() -> None:
    global _last_request_ts
    wait = _MIN_REQUEST_INTERVAL - (time.monotonic() - _last_request_ts)
    if wait > 0:
        time.sleep(wait)
    _last_request_ts = time.monotonic()


def fetch_stooq(stooq_symbol: str, start: str | None = None, retries: int = 3) -> pd.DataFrame:
    """Full (or from `start`) daily history from Stooq as an OHLCV frame.

    Stooq needs no API key but enforces a daily hits limit per IP; we throttle and
    raise RateLimitError when the limit is hit so callers can stop cleanly.
    """
    url = _STOOQ_URL.format(symbol=stooq_symbol)
    if start:
        url += "&d1=" + pd.Timestamp(start).strftime("%Y%m%d")
    for attempt in range(retries):
        _throttle()
        resp = requests.get(url, timeout=30, headers={"User-Agent": "trading-autoresearch/0.1"})
        text = resp.text
        if "Exceeded the daily hits limit" in text or "przekroczony dzienny limit" in text.lower():
            raise RateLimitError(f"Stooq daily limit hit while fetching {stooq_symbol}")
        if "requires JavaScript to verify your browser" in text:
            # Anti-bot verification page. We do not work around it — callers
            # should switch to the Yahoo backend instead.
            raise RateLimitError(
                f"Stooq is serving a browser-verification page for {stooq_symbol}; "
                "use the Yahoo backend"
            )
        if resp.status_code == 200 and text.startswith("Date,"):
            df = pd.read_csv(io.StringIO(text), parse_dates=["Date"], index_col="Date")
            df.columns = [c.lower() for c in df.columns]
            if "volume" not in df.columns:
                df["volume"] = float("nan")
            return df[OHLCV_COLS]
        if resp.status_code == 200 and text.strip().lower() in ("no data", "brak danych"):
            raise FileNotFoundError(f"Stooq has no data for {stooq_symbol}")
        time.sleep(2.0 * (attempt + 1))
    raise RuntimeError(
        f"Stooq fetch failed for {stooq_symbol}: HTTP {resp.status_code}, body starts "
        f"{text[:80]!r}"
    )


def fetch_yahoo_batch(yahoo_symbols: list[str], start: str | None = None) -> dict[str, pd.DataFrame]:
    """Batched Yahoo download via yfinance (primary backend).

    start=None fetches maximum available history. One yf.download call handles
    many tickers with shared session/throttling. Returns {yahoo_symbol: OHLCV
    frame}; symbols that fail are simply absent.
    """
    import yfinance as yf  # imported lazily; only scripts need it

    kwargs = dict(start=start) if start else dict(period="max")
    raw = yf.download(
        yahoo_symbols, interval="1d", group_by="ticker",
        auto_adjust=True, progress=False, threads=False, **kwargs,
    )
    out: dict[str, pd.DataFrame] = {}
    if raw is None or raw.empty:
        return out
    # yfinance >= 0.2.48 returns (Ticker, Price) MultiIndex columns even for a
    # single symbol (multi_level_index defaults to True); older versions
    # returned flat columns for one symbol. Select the ticker level whenever it
    # is there: treating a one-symbol MultiIndex frame as flat yields all-NaN
    # bars with tuple column names, which crashed the 2026-10-09 refresh.
    multi = isinstance(raw.columns, pd.MultiIndex)
    for sym in yahoo_symbols:
        if multi:
            if sym not in raw.columns.get_level_values(0):
                continue
            df = raw[sym]
        elif len(yahoo_symbols) == 1:
            df = raw
        else:
            continue
        df = df.dropna(how="all")
        if df.empty:
            continue
        df = df.rename(columns=str.lower)
        for col in OHLCV_COLS:
            if col not in df.columns:
                df[col] = float("nan")
        out[sym] = df[OHLCV_COLS]
    return out
