#!/usr/bin/env python
"""Forward (incubation) report: how registered candidates did on data that did
not exist when they were designed.

    python scripts/incubation_report.py                       # writes reports/incubation.md
    python scripts/incubation_report.py --out -               # print instead

`run_trial` freezes every v3 candidate that leads its family or reaches the
holdout gate into `strategies/incubating/` and appends it to
`experiments/incubation.jsonl` with the last date of the data it was judged on.
This script re-runs each frozen copy (refusing one whose sha256 changed) on the
full current panel under the v3 execution model and scores **only the trading
days after that date**, beside the equal-weight eligible pool on the same days.

This is the lab's answer to "does it work under current conditions": the
validation window ends in 2023 and the holdout has been partly read, but the
forward record is out-of-sample by construction. It accrues slowly — read
anything under ~1 year as an anecdote, which is why every row carries its
interval.

**Strategy sessions do not read this report** (CLAUDE.md): a forward number
that informs the next design stops being forward evidence for it.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from engine import data, metrics, protocol  # noqa: E402

OUT = protocol.ROOT / "reports" / "incubation.md"


def registrations() -> list[dict]:
    path = protocol.incubation_file()
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def score(entry: dict, prices: pd.DataFrame, aux: dict, setup: protocol.Setup) -> dict:
    copy = protocol.ROOT / entry["frozen_copy"]
    row = {"name": entry["name"], "family": entry["family"], "verdict": entry["verdict"],
           "registered": entry["ts"][:10], "data_end": entry["data_end"]}
    if not copy.exists():
        return row | {"error": "frozen copy missing"}
    if hashlib.sha256(copy.read_bytes()).hexdigest() != entry["sha256"]:
        return row | {"error": "frozen copy changed since registration (sha256 mismatch)"}
    mod, _ = protocol.load_strategy(copy)
    visible, elig = protocol.visible_frame(prices, None, setup)
    weights = protocol.call_strategy(*protocol._strategy_view(
        mod.generate_weights, visible, aux, elig, setup))
    res = protocol.run_backtest(weights, visible, eligible=elig, execution=setup.execution,
                                **protocol.ENGINE_PARAMS)
    after = res.returns.index > pd.Timestamp(entry["data_end"])
    fwd = res.returns.loc[after]
    pool = protocol.pool_returns(setup, visible, elig).reindex(fwd.index).fillna(0.0)
    row["days"] = int(len(fwd))
    if len(fwd) < 21:
        return row | {"note": "fewer than 21 forward days"}
    rf = setup.rf
    boot = metrics.sharpe_diff_bootstrap(fwd, pool, rf)
    return row | {
        "ann_return": metrics.ann_return(fwd), "sharpe": metrics.sharpe(fwd, rf),
        "pool_sharpe": metrics.sharpe(pool, rf), "skill": boot["diff"],
        "skill_lo": boot["lo"], "skill_hi": boot["hi"], "max_drawdown": metrics.max_drawdown(fwd),
        "validation_skill": entry.get("validation_skill"),
    }


def render(rows: list[dict]) -> str:
    lines = ["# Forward incubation report", "",
             "_Generated by `scripts/incubation_report.py`. Every number below is from trading days "
             "after the candidate was registered: data that did not exist when it was designed. "
             "Strategy sessions do not read this file._", "",
             "| candidate | family | verdict | registered | fwd days | ann. return | Sharpe | pool | "
             "skill | 90% CI | max DD | validation skill |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        if "skill" not in r:
            lines.append(f"| `{r['name']}` | {r['family']} | {r['verdict']} | {r['registered']} | "
                         f"{r.get('days', 0)} | {r.get('error') or r.get('note', '')} |||||||")
            continue
        vs = r.get("validation_skill")
        lines.append(
            f"| `{r['name']}` | {r['family']} | {r['verdict']} | {r['registered']} | {r['days']} | "
            f"{r['ann_return']:+.1%} | {r['sharpe']:+.2f} | {r['pool_sharpe']:+.2f} | "
            f"{r['skill']:+.2f} | [{r['skill_lo']:+.2f}, {r['skill_hi']:+.2f}] | "
            f"{r['max_drawdown']:.1%} | {'—' if vs is None else f'{vs:+.2f}'} |")
    if not rows:
        lines.append("| _no registrations yet_ ||||||||||||")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()
    regs = registrations()
    rows: list[dict] = []
    if regs:
        prices = data.load_prices(universe="pit", start=protocol.PIT_PRICE_START)
        aux = data.load_panels(universe="pit", start=protocol.PIT_PRICE_START)
        setup = protocol.setup_v3(prices, aux)
        for entry in regs:
            print(f"scoring {entry['name']} (registered {entry['ts'][:10]}) …")
            rows.append(score(entry, prices, aux, setup))
    text = render(rows)
    if args.out == "-":
        print(text)
    else:
        Path(args.out).write_text(text)
        print(f"written → {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
