#!/usr/bin/env python
"""Rank recorded trials with error bars, from stored validation returns only.

    python scripts/rank_trials.py                 # current protocol version
    python scripts/rank_trials.py --version 1     # an earlier version (Sharpe-only)
    python scripts/rank_trials.py --out reports/ranking-v3.md

No strategy is re-run and no split is read: everything comes from
`experiments/trials.jsonl` and `experiments/trial_returns/`. Trials recorded
under v3 carry the equal-weight pool and the cash rate beside their returns,
so they are ranked on skill (Sharpe minus the pool's); older trials are ranked
on Sharpe alone.

How to read the output: **tier 1 is the model confidence set** — the trials the
data cannot separate from the best at the 10% level. The order inside tier 1
is not evidence. Tier 2 is outside it but with a skill interval above zero;
tier 3 is everything else. `mechanism` groups trials whose active returns
correlate >= 0.5: one mechanism under several labels is one bet.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from engine import protocol, ranking  # noqa: E402


def collect(version: int) -> tuple[pd.DataFrame, pd.Series | None, pd.Series | None, dict]:
    rets, pools, rfs, meta = {}, [], [], {}
    for k, rec in enumerate(protocol.recorded_trials(version), 1):
        frame = protocol.load_trial_frame(rec.get("ts", ""), rec.get("name", ""))
        if frame is None or len(frame) < 100:
            continue
        key = f"#{k} {rec['name']}"
        rets[key] = frame["ret"]
        if "pool" in frame:
            pools.append(frame["pool"])
        if "rf" in frame:
            rfs.append(frame["rf"])
        meta[key] = {"family": rec.get("family"), "verdict": rec.get("verdict"),
                     "dsr": rec.get("dsr"), "train_skill": (rec.get("train") or {}).get("skill"),
                     "skill_cost2x": (rec.get("validation") or {}).get("skill_cost2x")}
    df = pd.DataFrame(rets)
    pool = pools[-1] if pools and len(pools) == len(rets) else None
    rf = rfs[-1] if rfs and len(rfs) == len(rets) else None
    return df, pool, rf, meta


def render(table: pd.DataFrame, meta: dict, version: int) -> str:
    skill = "skill" in table
    lines = [f"# Trial ranking with error bars — protocol v{version}", "",
             f"_Generated by `scripts/rank_trials.py` from stored validation returns "
             f"({table.attrs.get('n_days')} days); nothing was re-run._", ""]
    if skill:
        lines.append(f"Equal-weight eligible pool validation Sharpe: {table.attrs['pool_sharpe']:+.2f}. "
                     f"Skill = Sharpe minus the pool's on the same days (excess of T-bills).")
    lines += ["", "**Tier 1 is the set of trials the data cannot separate from the best (model "
              "confidence set, 10%). Order inside a tier is not evidence.**", ""]
    if skill:
        lines.append("| tier | trial | family | verdict | val Sharpe | skill | 90% CI | P(best) | "
                     "skill @2x cost | train skill | DSR | mechanism |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
    else:
        lines.append("| tier | trial | family | verdict | val Sharpe | 90% CI | P(best) | DSR |")
        lines.append("|---|---|---|---|---|---|---|---|")
    for name, r in table.iterrows():
        m = meta[name]
        fmt = lambda x: "—" if x is None or pd.isna(x) else f"{x:+.2f}"  # noqa: E731
        if skill:
            lines.append(
                f"| {r.tier} | `{name}` | {m['family']} | {m['verdict']} | {r.sharpe:+.2f} | "
                f"{r.skill:+.2f} | [{r.skill_lo:+.2f}, {r.skill_hi:+.2f}] | {r.p_best:.0%} | "
                f"{fmt(m['skill_cost2x'])} | {fmt(m['train_skill'])} | {m['dsr'] if m['dsr'] is not None else '—'} | "
                f"M{r.mechanism} |")
        else:
            lines.append(
                f"| {r.tier} | `{name}` | {m['family']} | {m['verdict']} | {r.sharpe:+.2f} | "
                f"[{r.sharpe_lo:+.2f}, {r.sharpe_hi:+.2f}] | {r.p_best:.0%} | "
                f"{m['dsr'] if m['dsr'] is not None else '—'} |")
    n1 = int((table["tier"] == 1).sum())
    lines += ["", f"{n1} of {len(table)} trials are in tier 1."]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", type=int, default=protocol.PROTOCOL_VERSION)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()
    df, pool, rf, meta = collect(args.version)
    if df.shape[1] == 0:
        print(f"no trials with stored validation returns under protocol v{args.version}")
        return 0
    table = ranking.rank_table(df, pool, rf)
    text = render(table, meta, args.version)
    if args.out:
        args.out.write_text(text)
        print(f"written → {args.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
